export const Strings = {
  PleaseWait: 'Please wait ...',
  RegisterDefaultTenant: 'Register Default Tenant',
  RestoreAccount: 'Restore Account',
  EnableFutureLogin: 'Please enable the following method for future login',
  TouchAndFaceId: 'TouchID /\n FaceID',
  About: 'About',
  DeviceAuth: 'Device Auth',
  LoginWithQR: 'Login with QR',
  LiveID: 'LiveID',
  FIDO2: 'FIDO2',
  PinManagement: 'Pin Management',
  ResetApp: 'Reset App',
  Copy: 'Copy',
  ORSession1: 'OR Session 1 \n (Scan qr ,authenticate with scope data)',
  ORSession2: 'OR Session 2 \n (Scan qr ,authenticate with preset data)',
  Register_PlatForm: 'Register (Platform Authenticator)',
  Authenticate_Platform: 'Authenticate (Platform Authenticator)',
  Register_Security_key: 'Register (Security key)',
  Authenticate_Security_key: 'Authenticate (Security Authenticator)',
  Register_Security_With_Pin: 'Register (Security key with Pin)',
  Authenticate_Security_With_Pin:
    'Authenticate (Security Authenticator with Pin)',
  Username: 'Username',
  Register_web: 'Register(Web)',
  Authenticate_Web: 'Authenticate (Web)',
  SetPin: 'Set Pin',
  ChangePin: 'Change Pin',
  ResetFIDO: 'Reset FIDO',
  FIDO2PINManagement: 'FIDO2 PIN Management',
  SetPIN: 'Set PIN',
  EnterTheNewPIN: 'Enter the New PIN',
  NewPIN: 'New PIN',
  ConfirmPIN: 'Confirm PIN',
  Cancel: 'Cancel',
  Done: 'Done',
  ChangePIN: 'ChangePIN',
  EnterTheKeyPIN: 'Enter the key PIN',
  currentPIN: 'current PIN',
  CancellationWarning: 'Cancellation Warning!',
  ResetFidoText: 'Do You Want To Reset FIDO?',
  NO: 'No',
  Yes: 'Yes',
  Warning: 'Warning!',
  resetAppText: 'Do you want to reset the app',
  Ok: 'Ok',
  PINVerificationRequired: 'PIN Verification Required',
  Verify: 'Verify',
  PIN: 'PIN',
  PleaseEnterValidPin: 'Please Enter Valid PIN',
  PinsDoNotMatch: 'Pins do not match',
  InvalidPin: 'Invalid Pin',
  CameraAccessAlertMessage: 'Please Enable the settings from device Settings',
  Successfully_Authenticated_Text:
    'You have successfully authenticated to Log In',
  Did: 'Did',
  Authenticate: 'Authenticate',
};
